# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('special', models.BooleanField(default=False)),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('prefix', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=4096)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('tracknum', models.SmallIntegerField(verbose_name='#')),
                ('filetype', models.CharField(choices=[('mp3', 'mp3'), ('ogg', 'ogg')], max_length=3)),
                ('bitrate', models.IntegerField()),
                ('mode', models.CharField(choices=[('ABR', 'ABR'), ('CBR', 'CBR'), ('VBR', 'VBR')], max_length=3)),
                ('size', models.IntegerField()),
                ('length', models.IntegerField()),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_updated', models.IntegerField(default=0)),
                ('sha256sum', models.CharField(max_length=64)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exordium.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exordium.Artist')),
                ('raw_artist', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exordium.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='normname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.RenameField(
            model_name='album',
            old_name='special',
            new_name='miscellaneous',
        ),
        migrations.AddField(
            model_name='album',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set([('artist', 'name')]),
        ),
        migrations.AddField(
            model_name='artist',
            name='normname',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='various',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composer_set', to='exordium.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='conductor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor_set', to='exordium.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='exordium.Artist'),
        ),
        migrations.AddField(
            model_name='song',
            name='raw_composer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='raw_conductor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='raw_group',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='raw_artist',
            field=models.CharField(max_length=255),
        ),
    ]
