# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0001_squashed_0002_auto_20160926_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('orig', 'Original'), ('album', 'Album Listing'), ('list', 'Inside Lists')], default='orig', max_length=5)),
                ('resolution', models.PositiveSmallIntegerField(default=0)),
                ('mime', models.CharField(max_length=64)),
                ('image', models.BinaryField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exordium.Album')),
            ],
        ),
    ]
