# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='normname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='normname',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
