# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0002_auto_20160918_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='raw_artist',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
