# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0003_song_raw_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
