# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0003_album_has_art'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='AlbumArt',
        ),
    ]
