# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0004_auto_20160919_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='special',
            new_name='miscellaneous',
        ),
    ]
