# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0004_auto_20160926_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumart',
            old_name='resolution',
            new_name='res_x',
        ),
        migrations.AddField(
            model_name='albumart',
            name='res_y',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
