# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0005_auto_20160919_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='various',
            field=models.BooleanField(default=False),
        ),
    ]
