# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0005_auto_20160926_1644'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumart',
            unique_together=set([('album', 'size')]),
        ),
    ]
