# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0006_auto_20160926_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumart',
            old_name='res_x',
            new_name='resolution',
        ),
        migrations.RemoveField(
            model_name='album',
            name='has_art',
        ),
        migrations.RemoveField(
            model_name='albumart',
            name='mime',
        ),
        migrations.RemoveField(
            model_name='albumart',
            name='res_y',
        ),
        migrations.AddField(
            model_name='album',
            name='art_ext',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AddField(
            model_name='album',
            name='art_filename',
            field=models.CharField(default=None, max_length=4096),
        ),
        migrations.AddField(
            model_name='album',
            name='art_mime',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='album',
            name='art_mtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='albumart',
            name='from_mtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='albumart',
            name='size',
            field=models.CharField(choices=[('album', 'Album Listing'), ('list', 'Inside Lists')], max_length=5),
        ),
    ]
