# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0006_artist_various'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
