# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0007_auto_20160926_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='art_ext',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='art_filename',
            field=models.CharField(default=None, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='art_mime',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='art_mtime',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
