# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0008_auto_20160927_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='normtitle',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
