# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exordium', '0009_auto_20160921_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='composer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composer_set', to='exordium.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='conductor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor_set', to='exordium.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='exordium.Artist'),
        ),
    ]
